model:
  class_path: src.model.clip.svl.FFGSynoVideoLearner
  init_args:
    num_frames: 10
    architecture: ViT-L/14
    face_feature_path: "misc/L14_real_semantic_patches_v2_2000.pickle"
trainer:
  accumulate_grad_batches: 1