class_path: lightning.pytorch.loggers.WandbLogger
init_args:
  name: null
  save_dir: './logs/'
  version: null
  offline: false
  dir: null
  id: null
  anonymous: null
  project: 'ECCV'
  log_model: false
  prefix: ''
  checkpoint_name: null
  entity: "aiiulab"