model:
  class_path: src.model.clip.svl.FFGSynoVideoLearner
  init_args:
    num_frames: 10
    architecture: ViT-B/16
    face_feature_path: "misc/B16_real_semantic_patches_v1_2000.pickle"
trainer:
  accumulate_grad_batches: 1