model:
  class_path: src.model.clip.svl.SynoVideoLearner
  init_args:
    num_frames: 10
    architecture: ViT-B/16
    ksize_s: 5
    ksize_t: 5
    s_k_attr: 'k' 
    s_v_attr: 'emb' 
    t_attrs: ["q","k","v","emb","out"]
trainer:
  accumulate_grad_batches: 1