model:
  class_path: src.model.clip.svl.SynoVideoLearner
  init_args:
    num_frames: 10
    architecture: ViT-L/14
    text_embed: false
    label_weights: [1.0,1.0]
trainer:
  accumulate_grad_batches: 1