model:
  class_path: src.model.clip.svl.FFGSynoVideoLearner
  init_args:
    num_frames: 10
    architecture: ViT-B/16
    face_feature_path: "misc/real_semantic_patches_v4_1000.pickle"
trainer:
  accumulate_grad_batches: 1