model:
  class_path: src.model.clip.snvl.CLIPBinaryVideoLearner
  init_args:
    num_layers: 12
    num_frames: 10
    num_queries: 2
    architecture: ViT-B/16
    with_frame: false
    label_weights: [2.0, 0.5]