model:
  class_path: src.model.clip.nsvl.NativeSummaryVideoLearner
  init_args:
    architecture: ViT-L/14
    prompt_mode: DEEP
    prompt_num: 1
    prompt_layers: 24
    prompt_dropout: 0.5
    text_embed: false
trainer:
  accumulate_grad_batches: 8