model:
  class_path: src.model.clip.snvl.CLIPBinaryVideoLearnerFFG
  init_args:
    out_dim: 2
    num_frames: 10
    num_queries: 2
    architecture: ViT-B/16
    layer_indices: [6,7,8,9,10,11]
    face_attn_attr: "k"
    face_parts: ["lips","skin"]
    face_feature_path: "misc/real_semantic_patches_v4_1000.pickle"