model:
  class_path: src.model.clip.svl.FFGSynoVideoLearner
  init_args:
    num_frames: 10
    architecture: ViT-L/14
    text_embed: false
    label_weights: [2.0, 0.5]
    face_parts: ["lips","skin","eyes","nose"]
    face_attn_attr: "k"
    syno_attn_attr: "s_q"
    face_feature_path: "misc/L14_real_semantic_patches_v2_2000.pickle"
    ffg_temper: 50
    ffg_weight: 0.1
    mask_ratio: 0.5
trainer:
  accumulate_grad_batches: 1