# lightning.pytorch==2.0.7
seed_everything: 1019
trainer:
  accelerator: auto
  strategy: auto
  devices: auto
  num_nodes: 1
  precision: 32-true
  logger:
    class_path: lightning.pytorch.loggers.WandbLogger
    init_args:
      name: null
      save_dir: './logs/'
      version: null
      offline: false
      dir: null
      id: null
      anonymous: null
      project: 'DFD-FFG'
      log_model: false
      prefix: ''
      checkpoint_name: null
  callbacks: null
  fast_dev_run: false
  max_epochs: 1
  min_epochs: null
  max_steps: -1
  min_steps: null
  max_time: null
  limit_train_batches: 0.01
  limit_val_batches: 10
  limit_test_batches: 0.01
  limit_predict_batches: 0.1
  overfit_batches: 0.0
  val_check_interval: null
  check_val_every_n_epoch: 1
  num_sanity_val_steps: null
  log_every_n_steps: 10
  enable_checkpointing: null
  enable_progress_bar: null
  enable_model_summary: null
  accumulate_grad_batches: 1
  gradient_clip_val: null
  gradient_clip_algorithm: null
  deterministic: null
  benchmark: null
  inference_mode: true
  use_distributed_sampler: true
  profiler: null
  detect_anomaly: false
  barebones: false
  plugins: null
  sync_batchnorm: false
  reload_dataloaders_every_n_epochs: 0
  default_root_dir: "./logs/"
early_stop:
  monitor: "valid/FFPP/loss"
  min_delta: 0.0
  patience: 10
  verbose: false
  mode: min
  strict: true
  check_finite: true
  stopping_threshold: null
  divergence_threshold: null
  check_on_train_epoch_end: null
  log_rank_zero_only: false
checkpoint:
  dirpath: null
  filename: null
  monitor: null
  verbose: false
  save_last: true
  save_top_k: 1
  save_weights_only: false
  mode: min
  auto_insert_metric_name: true
  every_n_train_steps: null
  train_time_interval: null
  every_n_epochs: null
  save_on_train_epoch_end: null
model:
  class_path: src.model.clip.CLIPLinearProbe
  init_args:
    output_dim: 2
data:
  class_path: src.dataset.base.ODDataModule
  init_args:
    train_datamodule:
      class_path: src.dataset.ffpp.FFPPDataModule
      init_args:
        df_types: ['REAL','DF','FS','F2F','NT']
        compressions: ['c23']
        strategy: CONTRAST_RAND
        augmentations: NONE
        force_random_speed: null
        data_dir: 'datasets/ffpp'
        batch_size: 12
        num_workers: 8
        vid_ext: .avi
        clip_duration: 1
        num_frames: 1
        pack: false
    val_datamodules:
    - class_path: src.dataset.cdf.CDFDataModule
      init_args:
        data_dir: 'datasets/cdf/'
        batch_size: 24
        num_workers: 8
        vid_ext: .avi
        clip_duration: 1
        num_frames: 1
        pack: false
    - class_path: src.dataset.dfdc.DFDCDataModule
      init_args:
        data_dir: 'datasets/dfdc/'
        batch_size: 24
        num_workers: 8
        vid_ext: .avi
        clip_duration: 1
        num_frames: 1
        pack: false
    test_datamodules:
    - class_path: src.dataset.ffpp.FFPPDataModule
      init_args:
        df_types: ['REAL','DF','FS','F2F','NT']
        compressions: ['c23']
        strategy: NORMAL
        augmentations: NONE
        force_random_speed: null
        data_dir: 'datasets/ffpp/'
        batch_size: 24
        num_workers: 8
        vid_ext: .avi
        clip_duration: 1
        num_frames: 1
        pack: false
