class_path: src.dataset.base.ODDeepFakeDataModule
init_args:
  batch_size: 24
  num_workers: 4
  clip_duration: 4
  num_frames: 10
  train_datamodules:
  - class_path: src.dataset.ffpp.FFPPDataModule
    init_args:
      df_types: ['REAL','DF','FS','F2F','NT']
      compressions: ['c23']
      strategy: CONTRAST_RAND
      augmentations:
      - NORMAL
      - VIDEO
      - VIDEO_RRC
      - FRAME
      force_random_speed: null
      data_dir: 'datasets/ffpp/'
      vid_ext: '.avi'
      pack: false
      max_clips: 3
  val_datamodules:
  - class_path: src.dataset.cdf.CDFDataModule
    init_args:
      data_dir: 'datasets/cdf/'
      vid_ext: '.avi'
      pack: false
  - class_path: src.dataset.dfdc.DFDCDataModule
    init_args:
      data_dir: 'datasets/dfdc/'
      vid_ext: '.avi'
      pack: false
  test_datamodules:
  - class_path: src.dataset.ffpp.FFPPDataModule
    init_args:
      df_types: ['REAL','DF','FS','F2F','NT']
      compressions: ['c23']
      strategy: NORMAL
      augmentations: 
      - NONE
      force_random_speed: null
      data_dir: 'datasets/ffpp/'
      vid_ext: '.avi'
      pack: false