data:
  class_path: src.dataset.base.ODDeepFakeDataModule
  init_args:
    batch_size: 50
    num_workers: 4
    clip_duration: 4
    num_frames: 10
    test_datamodules:
    - class_path: src.dataset.ffpp.FFPPDataModule
      init_args:
        df_types: ['REAL','FS']
        compressions: ['c23']
        strategy: NORMAL
        augmentations: 
        - NONE
        force_random_speed: null
        data_dir: 'datasets/ffpp/'
        vid_ext: .avi